### ISSUE TITLE
setting album name error

### ISSUE THREAD

**Issue by isthisthat** [Ciantic/songdetails#3]
I tried to set the album name to 'Arvanitaki' and it got stored as u'\u7241\u6176\u696e\u6174\u696b' which corresponds to 牁慶楮慴楫 :P Can you please look into that?
Great work, and thanks a lot!

**Comment by AVD087** [comment]
Looks like author busy making new code,
Let me suggest you solution,add u before your string, 
ex. **`song.album="Something"`** to **`song.album=u"Something"`**
It will work,happy coding.

**Comment by Ciantic** [comment]
Thanks for the tip, yes my OSS projects are mostly in dump and forget principle.

Closing because above 'fix' seems legit.
