### ISSUE TITLE
Impossible de retrieve year like "2010-09-25" (anything more than 4 digits)

### ISSUE THREAD

**Issue by julienpa** [Ciantic/songdetails#4]
I know that the ID3 "year" attribute is only supposed to be a four-digit number, but since ID3v2 you can set it to something which includes the month, the day and even the hour I think.
Anyway, when the "year" is something like "2010", it works very well, but if it's anything longer it stops working and the result becomes "None".
I tried to use the "TYER" ID3v2 attribute, but Python says that it doesn't exist in songdetails' object.
Any hint on that?
Thanks for this great module!

**Comment by Ciantic** [comment]
Decided to change a year to string
